version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: net50
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
