image: Visual Studio 2019

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus                  -c Release /p:EnableSourceLink=false
  - dotnet build Rebus.Tests.Contracts  -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
  - dotnet build Rebus.Tests            -c Release /p:WarningLevel=3 /p:EnableSourceLink=false

test_script:
  - dotnet test Rebus.Tests.Contracts --no-build --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
  - dotnet test Rebus.Tests --no-build --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
