name: .NET Ubuntu PR

on:
  pull_request:
    branches: [ master, release/7 ]
    paths-ignore:
    - '**.md'
    - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:EnableSourceLink=false
    - name: Test Contracts
      run: dotnet test Rebus.Tests.Contracts --no-build --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
    - name: Test
      run: dotnet test Rebus.Tests --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
