name: .NET windows PR

on:
  pull_request:
    branches: [ master, release/7 ]
    paths-ignore:
    - '**.md'
    - '.github/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .Net 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run:  |
        dotnet nuget locals all --clear
        dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:EnableSourceLink=false
    - name: Test Contracts
      run: dotnet test Rebus.Tests.Contracts --no-build --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
    - name: Test
      run: dotnet test Rebus.Tests --no-build --verbosity normal -c Release /p:WarningLevel=3 /p:EnableSourceLink=false
